[package]
name = "tofnd"
version = "0.3.0"
authors = ["Gus Gutoski <gus@axelar.network>", "Stelios Daveas <stelios@axelar.network>"]
edition = "2018"

[dependencies]
tonic = "0.5"
tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git", branch = "main"}
# tofn = { path = "../tofn" }
bincode = "1.2.1"
sled = "0.34"
testdir = "0.4.0"

# logging
log = "0.4"
tracing = "0.1"
tracing-subscriber= {version = "0.2", features = ["json"] }
atty = "*"

# config
clap = "2.33"

# sled dependency
serde = { version = "1.0", features = ["derive"] }

# tonic dependencies
prost = "0.8"
tokio = { version = "1.8", features = ["rt-multi-thread", "macros", "signal", "net", "sync"] }
tokio-stream = {version = "0.1.7", features = ["net"]}
futures-util = "0.3"

# mnemonic
tiny-bip39 = "0.8.0"
zeroize = "1.3"

[build-dependencies]
tonic-build = "0.5"

[dev-dependencies]
lazy_static = "1.4"
# enable logging for tests
tracing-test = "0.1.0"
# iterate enums
strum = "0.20"
strum_macros = "0.20"

[features]
# when we compile tofnd with malicious build, also use malicious build for tofn
malicious = ["tofn/malicious"]
