[package]
name = "tofnd"
version = "0.1.0"
authors = ["Gus Gutoski <gus@axelar.network>"]
edition = "2018"

[dependencies]
tonic = "0.3"
tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git" }
# tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git", branch = "feat/honest-behaviour"}
# tofn = { path = "../tofn" }
bincode = "1.2.1"
sled = "0.34"
funty = "=1.1.0" # zengo baggage
testdir = "0.4.0"

# logging
log = "0.4"
tracing = "0.1"
tracing-subscriber = "0.2"
atty = "*"

# config
clap = "2.33"

# sled dependency
serde = { version = "1.0", features = ["derive"] }

# tonic dependencies
prost = "0.6"
tokio = { version = "0.2", features = ["macros", "signal"] }
futures-util = "0.3"

[build-dependencies]
tonic-build = "0.3"

[dev-dependencies]
lazy_static = "1.4"
# enable logging for tests
tracing-test = "0.1.0"

[features]
malicious = []
