[package]
name = "tofnd"
version = "0.1.0"
authors = ["Gus Gutoski <gus@axelar.network>"]
edition = "2018"

[dependencies]
tonic = "0.3"
# tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git" }
tofn = { git = "ssh://git@github.com/axelarnetwork/tofn.git", branch = "sign"}
# tofn = { path = "../tofn" }
bincode = "1.2.1"
microkv = "0.2.6"

# microkv dependency
serde = { version = "1.0", features = ["derive"] }

# tonic dependencies
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
futures-util = "0.3"

[build-dependencies]
tonic-build = "0.3"

[dev-dependencies]
lazy_static = "1.4"