[package]
name = "tssd"
version = "0.1.0"
authors = ["Gus Gutoski <gus@axelar.network>"]
edition = "2018"

[dependencies]
tonic = "0.3"
# serde = { version = "1.0", features = ["derive"] }
# bincode = "1.3.1"

# tonic dependencies
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }
# futures-core = "0.3"
futures-util = "0.3"

[build-dependencies]
tonic-build = "0.3"