# usage:
# $ docker-compose up
# or
# $ docker-compose run -e MNEMONIC_CMD=<mnemonic_cmd> tofnd

volumes:
  tofnd:

services:
  tofnd:
    build: .
    container_name: tofnd
    hostname: tofnd
    image: axelar/tofnd
    volumes:
      - tofnd:/.tofnd
    environment:
      # available cmds: auto, create (default), stored, update, import, export
      - MNEMONIC_CMD=auto
