volumes:
  tofnd:

services:
  tofnd:
    build: .
    container_name: tofnd
    hostname: tofnd
    image: axelar/tofnd
    volumes:
      - tofnd:/.tofnd
    # Attention! Use --unsafe only for testing
    environment:
      - UNSAFE_FLAG=--unsafe
