volumes:
  tofnd:

services:
  tofnd:
    build: .
    container_name: tofnd
    hostname: tofnd
    image: axelar/tofnd
    volumes:
      - tofnd:/.tofnd
    environment:
      # Attention! Use UNSAFE=true only for testing
      - UNSAFE=true
      - NOPASSWORD=true
