volumes:
  tofnd:

services:
  tofnd:
    build: .
    container_name: tofnd
    hostname: tofnd
    image: axelar/tofnd
    volumes:
      - tofnd:/.tofnd
    # Attention! Use UNSAFE=true only for testing
    environment:
      - UNSAFE=true
