name: Test build binaries

on:
  push:
    branches:
      - feat/arm-support

jobs:
  release-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
        arch: [amd64, arm64]
        exclude:
          - {os: "ubuntu-18.04", arch: "arm64"}

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          ref: ${{ github.event.inputs.tag }}
          submodules: recursive

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: build darwin binaries
        env: 
          SEMVER: v1.1.1
        if: matrix.os == 'macos-latest'
        run: |
          OS="darwin"
          ARCH="${{ matrix.arch }}" 
          if [ "$ARCH" == "arm64" ]
          then
            export HOMEBREW_NO_INSTALL_CLEANUP=TRUE
            brew uninstall --ignore-dependencies gmp
            rustup target add aarch64-apple-darwin
            ARM_DEPENDENCY=$(brew fetch --force --bottle-tag=arm64_big_sur gmp | grep Downloaded | awk '{print $3}')
            brew install "$ARM_DEPENDENCY"
            cargo build --release --target aarch64-apple-darwin
            mkdir tofndbin
            mv /Users/runner/work/tofnd/tofnd/target/aarch64-apple-darwin/release/tofnd "./tofndbin/tofnd-$OS-$ARCH-$SEMVER"
          else
            cargo install --locked --path .
            mkdir tofndbin
            mv "/Users/runner/work/tofnd/tofnd/target/release/tofnd" "./tofndbin/tofnd-$OS-$ARCH-$SEMVER"
          fi

      - name: build linux binaries
        env: 
          SEMVER: v1.1.1
        if: matrix.os == 'ubuntu-18.04'
        run: |
          OS="linux"
          ARCH="${{ matrix.arch }}" 
            cargo install --locked --path .
            mkdir tofndbin
            mv "/home/runner/work/tofnd/tofnd/target/release/tofnd" "./tofndbin/tofnd-$OS-$ARCH-$SEMVER"

      - name: Test tofnd
        working-directory: ./tofndbin
        run: |
          file ./tofnd-*

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign binaries
        working-directory: ./tofndbin
        env:
          SEMVER: v1.1.1
        run: |
          if [ "$RUNNER_OS" == "Linux" ]
          then
              OS="linux"
          else
              OS="darwin"
          fi
          ARCH="${{ matrix.arch }}" 
          gpg --armor --detach-sign  tofnd-"$OS"-"$ARCH"-"$SEMVER"

      - name: Create zip and sha256 files
        working-directory: ./tofndbin
        run: |
          for i in `ls | grep -v .asc`
          do
            shasum -a 256 $i | awk '{print $1}' > $i.sha256
            zip $i.zip $i
            shasum -a 256 $i.zip | awk '{print $1}' > $i.zip.sha256
          done


